# Generated by Django 4.1.6 on 2023-02-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
